name: Build Project

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
          
          - name: macOS
            os: macos-latest

          - name: Linux
            os: ubuntu-latest
    
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Deps (win)
        if: matrix.config.os == 'Windows'
        run: |
          choco install cmake ninja ffmpeg clang -y
      
      - name: Deps (mac)
        if: matrix.config.os == "macOS"
        run: |
          brew update
          brew install cmake ninja ffmpeg clang

      - name: Deps (lin)
        if: matrix.config.os == "Linux"
        run: |
          sudo apt-get update
          sudo apt-get install -y cmake ninja-build ffmpeg clang

      - name: Configure
        run: cmake -S . -B build -G Ninja -DCMAKE_BUILD_TYPE=Release

      - name: Compile
        run: cmake --build build --config Release
