name: Build Project

on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        config:
          - name: Windows
            os: windows-latest
          
          - name: macOS
            os: macos-latest

          - name: Linux
            os: ubuntu-latest
    
    name: ${{ matrix.config.name }}
    runs-on: ${{ matrix.config.os }}

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Deps (win)
        if: runner.os == 'Windows'
        run: |
          choco install cmake pkgconfiglite mingw -y

          curl -L -o ffmpeg-dev.zip https://github.com/BtbN/FFmpeg-Builds/releases/download/latest/ffmpeg-n4.5-latest-win64-gpl-shared.zip
          mkdir C:\ffmpeg
          powershell -Command "Expand-Archive ffmpeg-dev.zip C:\ffmpeg"

          # Set environment variables for CMake to find FFmpeg
          echo "CMAKE_PREFIX_PATH=C:\\ffmpeg" >> $GITHUB_ENV
          echo "PATH=C:\\ffmpeg\\bin;$Env:PATH" >> $GITHUB_ENV
      
      - name: Deps (mac)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install cmake ninja ffmpeg@7
          brew link --force ffmpeg@7

      - name: Deps (lin)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential git yasm nasm make \
          pkg-config cmake ninja-build gnome-desktop-testing libasound2-dev libpulse-dev \
          libaudio-dev libjack-dev libsndio-dev libx11-dev libxext-dev \
          libxrandr-dev libxcursor-dev libxfixes-dev libxi-dev libxss-dev libxtst-dev \
          libxkbcommon-dev libdrm-dev libgbm-dev libgl1-mesa-dev libgles2-mesa-dev \
          libegl1-mesa-dev libdbus-1-dev libibus-1.0-dev libudev-dev clang ffmpeg libavutil-dev \
          libavcodec-dev libavformat-dev libswscale-dev libswresample-dev

          git clone https://github.com/FFmpeg/FFmpeg.git
          cd FFmpeg
          git checkout n7.1.1
          ./configure --prefix=$HOME/ffmpeg7 --enable-shared --disable-doc --disable-programs
          make -j$(nproc)
          make install

          export PKG_CONFIG_PATH=$HOME/ffmpeg7/lib/pkgconfig:$PKG_CONFIG_PATH
          export PATH=$HOME/ffmpeg7/bin:$PATH
          export LD_LIBRARY_PATH=$HOME/ffmpeg7/lib:$LD_LIBRARY_PATH

          cd ..

      - name: Configure (win)
        if: runner.os == 'Windows'
        run: cmake -S . -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release

      - name: Configure (everyone else)
        run: cmake -S . -B build -G Ninja -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=Release

      - name: Compile
        run: cmake --build build --config Release
